"use strict";
/**
 * Portions Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UNICODE_MISTAKES = new Map();
exports.UNICODE_MISTAKES.set('\u07fa', ['Nko Lajanyalan', '_']);
exports.UNICODE_MISTAKES.set('\ufe4d', ['Dashed Low Line', '_']);
exports.UNICODE_MISTAKES.set('\ufe4e', ['Centreline Low Line', '_']);
exports.UNICODE_MISTAKES.set('\ufe4f', ['Wavy Low Line', '_']);
exports.UNICODE_MISTAKES.set('\uff3f', ['Fullwidth Low Line', '_']);
exports.UNICODE_MISTAKES.set('\u2010', ['Hyphen', '-']);
exports.UNICODE_MISTAKES.set('\u2011', ['Non-Breaking Hyphen', '-']);
exports.UNICODE_MISTAKES.set('\u2012', ['Figure Dash', '-']);
exports.UNICODE_MISTAKES.set('\u2013', ['En Dash', '-']);
exports.UNICODE_MISTAKES.set('\u2014', ['Em Dash', '-']);
exports.UNICODE_MISTAKES.set('\ufe58', ['Small Em Dash', '-']);
exports.UNICODE_MISTAKES.set('\u06d4', ['Arabic Full Stop', '-']);
exports.UNICODE_MISTAKES.set('\u2043', ['Hyphen Bullet', '-']);
exports.UNICODE_MISTAKES.set('\u02d7', ['Modifier Letter Minus Sign', '-']);
exports.UNICODE_MISTAKES.set('\u2212', ['Minus Sign', '-']);
exports.UNICODE_MISTAKES.set('\u2796', ['Heavy Minus Sign', '-']);
exports.UNICODE_MISTAKES.set('\u2cba', ['Coptic Letter Dialect-P Ni', '-']);
exports.UNICODE_MISTAKES.set('\u30fc', ['Katakana-Hiragana Prolonged Sound Mark', '-']);
exports.UNICODE_MISTAKES.set('\uff0d', ['Fullwidth Hyphen-Minus', '-']);
exports.UNICODE_MISTAKES.set('\u2015', ['Horizontal Bar', '-']);
exports.UNICODE_MISTAKES.set('\u2500', ['Box Drawings Light Horizontal', '-']);
exports.UNICODE_MISTAKES.set('\u2501', ['Box Drawings Heavy Horizontal', '-']);
exports.UNICODE_MISTAKES.set('\u31d0', ['CJK Stroke H', '-']);
exports.UNICODE_MISTAKES.set('\ua7f7', ['Latin Epigraphic Letter Dideways', '-']);
exports.UNICODE_MISTAKES.set('\u1173', ['Hangul Jungseong Eu', '-']);
exports.UNICODE_MISTAKES.set('\u3161', ['Hangul Letter Eu', '-']);
exports.UNICODE_MISTAKES.set('\u4e00', ['CJK Unified Ideograph-4E00', '-']);
exports.UNICODE_MISTAKES.set('\u2f00', ['Kangxi Radical One', '-']);
exports.UNICODE_MISTAKES.set('\u060d', ['Arabic Date Separator', ',']);
exports.UNICODE_MISTAKES.set('\u066b', ['Arabic Decimal Separator', ',']);
exports.UNICODE_MISTAKES.set('\u201a', ['Single Low-9 Quotation Mark', ',']);
exports.UNICODE_MISTAKES.set('\xb8', ['Cedilla', ',']);
exports.UNICODE_MISTAKES.set('\ua4f9', ['Lisu Letter Tone Na Po', ',']);
exports.UNICODE_MISTAKES.set('\uff0c', ['Fullwidth Comma', ',']);
exports.UNICODE_MISTAKES.set('\u037e', ['Greek Question Mark', ';']);
exports.UNICODE_MISTAKES.set('\uff1b', ['Fullwidth Semicolon', ';']);
exports.UNICODE_MISTAKES.set('\ufe14', ['Presentation Form For Vertical Semicolon', ';']);
exports.UNICODE_MISTAKES.set('\u0903', ['Devanagari Sign Visarga', ':']);
exports.UNICODE_MISTAKES.set('\u0a83', ['Gujarati Sign Visarga', ':']);
exports.UNICODE_MISTAKES.set('\uff1a', ['Fullwidth Colon', ':']);
exports.UNICODE_MISTAKES.set('\u0589', ['Armenian Full Stop', ':']);
exports.UNICODE_MISTAKES.set('\u0703', ['Syriac Supralinear Colon', ':']);
exports.UNICODE_MISTAKES.set('\u0704', ['Syriac Sublinear Colon', ':']);
exports.UNICODE_MISTAKES.set('\u16ec', ['Runic Multiple Punctuation', ':']);
exports.UNICODE_MISTAKES.set('\ufe30', ['Presentation Form For Vertical Two Dot Leader', ':']);
exports.UNICODE_MISTAKES.set('\u1803', ['Mongolian Full Stop', ':']);
exports.UNICODE_MISTAKES.set('\u1809', ['Mongolian Manchu Full Stop', ':']);
exports.UNICODE_MISTAKES.set('\u205a', ['Two Dot Punctuation', ':']);
exports.UNICODE_MISTAKES.set('\u05c3', ['Hebrew Punctuation Sof Pasuq', ':']);
exports.UNICODE_MISTAKES.set('\u02f8', ['Modifier Letter Raised Colon', ':']);
exports.UNICODE_MISTAKES.set('\ua789', ['Modifier Letter Colon', ':']);
exports.UNICODE_MISTAKES.set('\u2236', ['Ratio', ':']);
exports.UNICODE_MISTAKES.set('\u02d0', ['Modifier Letter Triangular Colon', ':']);
exports.UNICODE_MISTAKES.set('\ua4fd', ['Lisu Letter Tone Mya Jeu', ':']);
exports.UNICODE_MISTAKES.set('\ufe13', ['Presentation Form For Vertical Colon', ':']);
exports.UNICODE_MISTAKES.set('\uff01', ['Fullwidth Exclamation Mark', '!']);
exports.UNICODE_MISTAKES.set('\u01c3', ['Latin Letter Retroflex Click', '!']);
exports.UNICODE_MISTAKES.set('\u2d51', ['Tifinagh Letter Tuareg Yang', '!']);
exports.UNICODE_MISTAKES.set('\ufe15', ['Presentation Form For Vertical Exclamation Mark', '!']);
exports.UNICODE_MISTAKES.set('\u0294', ['Latin Letter Glottal Stop', '?']);
exports.UNICODE_MISTAKES.set('\u0241', ['Latin Capital Letter Glottal Stop', '?']);
exports.UNICODE_MISTAKES.set('\u097d', ['Devanagari Letter Glottal Stop', '?']);
exports.UNICODE_MISTAKES.set('\u13ae', ['Cherokee Letter He', '?']);
exports.UNICODE_MISTAKES.set('\ua6eb', ['Bamum Letter Ntuu', '?']);
exports.UNICODE_MISTAKES.set('\uff1f', ['Fullwidth Question Mark', '?']);
exports.UNICODE_MISTAKES.set('\ufe16', ['Presentation Form For Vertical Question Mark', '?']);
exports.UNICODE_MISTAKES.set('\u{1d16d}', ['Musical Symbol Combining Augmentation Dot', '.']);
exports.UNICODE_MISTAKES.set('\u2024', ['One Dot Leader', '.']);
exports.UNICODE_MISTAKES.set('\u0701', ['Syriac Supralinear Full Stop', '.']);
exports.UNICODE_MISTAKES.set('\u0702', ['Syriac Sublinear Full Stop', '.']);
exports.UNICODE_MISTAKES.set('\ua60e', ['Vai Full Stop', '.']);
exports.UNICODE_MISTAKES.set('\u{10a50}', ['Kharoshthi Punctuation Dot', '.']);
exports.UNICODE_MISTAKES.set('\u0660', ['Arabic-Indic Digit Zero', '.']);
exports.UNICODE_MISTAKES.set('\u06f0', ['Extended Arabic-Indic Digit Zero', '.']);
exports.UNICODE_MISTAKES.set('\ua4f8', ['Lisu Letter Tone Mya Ti', '.']);
exports.UNICODE_MISTAKES.set('\xb7', ['Middle Dot', '.']);
exports.UNICODE_MISTAKES.set('\u30fb', ['Katakana Middle Dot', '.']);
exports.UNICODE_MISTAKES.set('\uff65', ['Halfwidth Katakana Middle Dot', '.']);
exports.UNICODE_MISTAKES.set('\u16eb', ['Runic Single Punctuation', '.']);
exports.UNICODE_MISTAKES.set('\u0387', ['Greek Ano Teleia', '.']);
exports.UNICODE_MISTAKES.set('\u2e31', ['Word Separator Middle Dot', '.']);
exports.UNICODE_MISTAKES.set('\u{10101}', ['Aegean Word Separator Dot', '.']);
exports.UNICODE_MISTAKES.set('\u2022', ['Bullet', '.']);
exports.UNICODE_MISTAKES.set('\u2027', ['Hyphenation Point', '.']);
exports.UNICODE_MISTAKES.set('\u2219', ['Bullet Operator', '.']);
exports.UNICODE_MISTAKES.set('\u22c5', ['Dot Operator', '.']);
exports.UNICODE_MISTAKES.set('\ua78f', ['Latin Letter Sinological Dot', '.']);
exports.UNICODE_MISTAKES.set('\u1427', ['Canadian Syllabics Final Middle Dot', '.']);
exports.UNICODE_MISTAKES.set('\u1427', ['Canadian Syllabics Final Middle Dot', '.']);
exports.UNICODE_MISTAKES.set('\uff0e', ['Fullwidth Full Stop', '.']);
exports.UNICODE_MISTAKES.set('\u3002', ['Ideographic Full Stop', '.']);
exports.UNICODE_MISTAKES.set('\ufe12', ['Presentation Form For Vertical Ideographic Full Stop', '.']);
exports.UNICODE_MISTAKES.set('\u055d', ['Armenian Comma', "'"]);
exports.UNICODE_MISTAKES.set('\uff07', ['Fullwidth Apostrophe', "'"]);
exports.UNICODE_MISTAKES.set('\u2018', ['Left Single Quotation Mark', "'"]);
exports.UNICODE_MISTAKES.set('\u2019', ['Right Single Quotation Mark', "'"]);
exports.UNICODE_MISTAKES.set('\u201b', ['Single High-Reversed-9 Quotation Mark', "'"]);
exports.UNICODE_MISTAKES.set('\u2032', ['Prime', "'"]);
exports.UNICODE_MISTAKES.set('\u2035', ['Reversed Prime', "'"]);
exports.UNICODE_MISTAKES.set('\u055a', ['Armenian Apostrophe', "'"]);
exports.UNICODE_MISTAKES.set('\u05f3', ['Hebrew Punctuation Geresh', "'"]);
exports.UNICODE_MISTAKES.set('`', ['Grave Accent', "'"]);
exports.UNICODE_MISTAKES.set('\u1fef', ['Greek Varia', "'"]);
exports.UNICODE_MISTAKES.set('\uff40', ['Fullwidth Grave Accent', "'"]);
exports.UNICODE_MISTAKES.set('\xb4', ['Acute Accent', "'"]);
exports.UNICODE_MISTAKES.set('\u0384', ['Greek Tonos', "'"]);
exports.UNICODE_MISTAKES.set('\u1ffd', ['Greek Oxia', "'"]);
exports.UNICODE_MISTAKES.set('\u1fbd', ['Greek Koronis', "'"]);
exports.UNICODE_MISTAKES.set('\u1fbf', ['Greek Psili', "'"]);
exports.UNICODE_MISTAKES.set('\u1ffe', ['Greek Dasia', "'"]);
exports.UNICODE_MISTAKES.set('\u02b9', ['Modifier Letter Prime', "'"]);
exports.UNICODE_MISTAKES.set('\u0374', ['Greek Numeral Sign', "'"]);
exports.UNICODE_MISTAKES.set('\u02c8', ['Modifier Letter Vertical Line', "'"]);
exports.UNICODE_MISTAKES.set('\u02ca', ['Modifier Letter Acute Accent', "'"]);
exports.UNICODE_MISTAKES.set('\u02cb', ['Modifier Letter Grave Accent', "'"]);
exports.UNICODE_MISTAKES.set('\u02f4', ['Modifier Letter Middle Grave Accent', "'"]);
exports.UNICODE_MISTAKES.set('\u02bb', ['Modifier Letter Turned Comma', "'"]);
exports.UNICODE_MISTAKES.set('\u02bd', ['Modifier Letter Reversed Comma', "'"]);
exports.UNICODE_MISTAKES.set('\u02bc', ['Modifier Letter Apostrophe', "'"]);
exports.UNICODE_MISTAKES.set('\u02be', ['Modifier Letter Right Half Ring', "'"]);
exports.UNICODE_MISTAKES.set('\ua78c', ['Latin Small Letter Saltillo', "'"]);
exports.UNICODE_MISTAKES.set('\u05d9', ['Hebrew Letter Yod', "'"]);
exports.UNICODE_MISTAKES.set('\u07f4', ['Nko High Tone Apostrophe', "'"]);
exports.UNICODE_MISTAKES.set('\u07f5', ['Nko Low Tone Apostrophe', "'"]);
exports.UNICODE_MISTAKES.set('\u144a', ['Canadian Syllabics West-Cree P', "'"]);
exports.UNICODE_MISTAKES.set('\u16cc', ['Runic Letter Short-Twig-Sol S', "'"]);
exports.UNICODE_MISTAKES.set('\u{16f51}', ['Miao Sign Aspiration', "'"]);
exports.UNICODE_MISTAKES.set('\u{16f52}', ['Miao Sign Reformed Voicing', "'"]);
exports.UNICODE_MISTAKES.set('\u1cd3', ['Vedic Sign Nihshvasa', '"']);
exports.UNICODE_MISTAKES.set('\uff02', ['Fullwidth Quotation Mark', '"']);
exports.UNICODE_MISTAKES.set('\u201c', ['Left Double Quotation Mark', '"']);
exports.UNICODE_MISTAKES.set('\u201d', ['Right Double Quotation Mark', '"']);
exports.UNICODE_MISTAKES.set('\u201f', ['Double High-Reversed-9 Quotation Mark', '"']);
exports.UNICODE_MISTAKES.set('\u2033', ['Double Prime', '"']);
exports.UNICODE_MISTAKES.set('\u2036', ['Reversed Double Prime', '"']);
exports.UNICODE_MISTAKES.set('\u3003', ['Ditto Mark', '"']);
exports.UNICODE_MISTAKES.set('\u05f4', ['Hebrew Punctuation Gershayim', '"']);
exports.UNICODE_MISTAKES.set('\u02dd', ['Double Acute Accent', '"']);
exports.UNICODE_MISTAKES.set('\u02ba', ['Modifier Letter Double Prime', '"']);
exports.UNICODE_MISTAKES.set('\u02f6', ['Modifier Letter Middle Double Acute Accent', '"']);
exports.UNICODE_MISTAKES.set('\u02f5', ['Modifier Letter Middle Double Grave Accent', '"']);
exports.UNICODE_MISTAKES.set('\u02ee', ['Modifier Letter Double Apostrophe', '"']);
exports.UNICODE_MISTAKES.set('\u05f2', ['Hebrew Ligature Yiddish Double Yod', '"']);
exports.UNICODE_MISTAKES.set('\u275e', ['Heavy Double Comma Quotation Mark Ornament', '"']);
exports.UNICODE_MISTAKES.set('\u275d', ['Heavy Double Turned Comma Quotation Mark Ornament', '"']);
exports.UNICODE_MISTAKES.set('\uff08', ['Fullwidth Left Parenthesis', '(']);
exports.UNICODE_MISTAKES.set('\u2768', ['Medium Left Parenthesis Ornament', '(']);
exports.UNICODE_MISTAKES.set('\ufd3e', ['Ornate Left Parenthesis', '(']);
exports.UNICODE_MISTAKES.set('\uff09', ['Fullwidth Right Parenthesis', ')']);
exports.UNICODE_MISTAKES.set('\u2769', ['Medium Right Parenthesis Ornament', ')']);
exports.UNICODE_MISTAKES.set('\ufd3f', ['Ornate Right Parenthesis', ')']);
exports.UNICODE_MISTAKES.set('\uff3b', ['Fullwidth Left Square Bracket', '[']);
exports.UNICODE_MISTAKES.set('\u2772', ['Light Left Tortoise Shell Bracket Ornament', '[']);
exports.UNICODE_MISTAKES.set('\u300c', ['Left Corner Bracket', '[']);
exports.UNICODE_MISTAKES.set('\u300e', ['Left White Corner Bracket', '[']);
exports.UNICODE_MISTAKES.set('\u3010', ['Left Black Lenticular Bracket', '[']);
exports.UNICODE_MISTAKES.set('\u3014', ['Left Tortoise Shell Bracket', '[']);
exports.UNICODE_MISTAKES.set('\u3016', ['Left White Lenticular Bracket', '[']);
exports.UNICODE_MISTAKES.set('\u3018', ['Left White Tortoise Shell Bracket', '[']);
exports.UNICODE_MISTAKES.set('\u301a', ['Left White Square Bracket', '[']);
exports.UNICODE_MISTAKES.set('\uff3d', ['Fullwidth Right Square Bracket', ']']);
exports.UNICODE_MISTAKES.set('\u2773', ['Light Right Tortoise Shell Bracket Ornament', ']']);
exports.UNICODE_MISTAKES.set('\u300d', ['Right Corner Bracket', ']']);
exports.UNICODE_MISTAKES.set('\u300f', ['Right White Corner Bracket', ']']);
exports.UNICODE_MISTAKES.set('\u3011', ['Right Black Lenticular Bracket', ']']);
exports.UNICODE_MISTAKES.set('\u3015', ['Right Tortoise Shell Bracket', ']']);
exports.UNICODE_MISTAKES.set('\u3017', ['Right White Lenticular Bracket', ']']);
exports.UNICODE_MISTAKES.set('\u3019', ['Right White Tortoise Shell Bracket', ']']);
exports.UNICODE_MISTAKES.set('\u301b', ['Right White Square Bracket', ']']);
exports.UNICODE_MISTAKES.set('\u2774', ['Medium Left Curly Bracket Ornament', '{']);
exports.UNICODE_MISTAKES.set('\u{1d114}', ['Musical Symbol Brace', '{']);
exports.UNICODE_MISTAKES.set('\uff5b', ['Fullwidth Left Curly Bracket', '{']);
exports.UNICODE_MISTAKES.set('\u2775', ['Medium Right Curly Bracket Ornament', '}']);
exports.UNICODE_MISTAKES.set('\uff5d', ['Fullwidth Right Curly Bracket', '}']);
exports.UNICODE_MISTAKES.set('\u204e', ['Low Asterisk', '*']);
exports.UNICODE_MISTAKES.set('\u066d', ['Arabic Five Pointed Star', '*']);
exports.UNICODE_MISTAKES.set('\u2217', ['Asterisk Operator', '*']);
exports.UNICODE_MISTAKES.set('\u{1031f}', ['Old Italic Letter Ess', '*']);
exports.UNICODE_MISTAKES.set('\uff0a', ['Fullwidth Asterisk', '*']);
exports.UNICODE_MISTAKES.set('\u1735', ['Philippine Single Punctuation', '/']);
exports.UNICODE_MISTAKES.set('\u2041', ['Caret Insertion Point', '/']);
exports.UNICODE_MISTAKES.set('\u2215', ['Division Slash', '/']);
exports.UNICODE_MISTAKES.set('\u2044', ['Fraction Slash', '/']);
exports.UNICODE_MISTAKES.set('\u2571', ['Box Drawings Light Diagonal Upper Right To Lower Left', '/']);
exports.UNICODE_MISTAKES.set('\u27cb', ['Mathematical Rising Diagonal', '/']);
exports.UNICODE_MISTAKES.set('\u29f8', ['Big Solidus', '/']);
exports.UNICODE_MISTAKES.set('\u{1d23a}', ['Greek Instrumental Notation Symbol-47', '/']);
exports.UNICODE_MISTAKES.set('\u31d3', ['CJK Stroke Sp', '/']);
exports.UNICODE_MISTAKES.set('\u3033', ['Vertical Kana Repeat Mark Upper Half', '/']);
exports.UNICODE_MISTAKES.set('\u2cc6', ['Coptic Capital Letter Old Coptic Esh', '/']);
exports.UNICODE_MISTAKES.set('\u30ce', ['Katakana Letter No', '/']);
exports.UNICODE_MISTAKES.set('\u4e3f', ['CJK Unified Ideograph-4E3F', '/']);
exports.UNICODE_MISTAKES.set('\u2f03', ['Kangxi Radical Slash', '/']);
exports.UNICODE_MISTAKES.set('\uff0f', ['Fullwidth Solidus', '/']);
exports.UNICODE_MISTAKES.set('\uff3c', ['Fullwidth Reverse Solidus', '\\']);
exports.UNICODE_MISTAKES.set('\ufe68', ['Small Reverse Solidus', '\\']);
exports.UNICODE_MISTAKES.set('\u2216', ['Set Minus', '\\']);
exports.UNICODE_MISTAKES.set('\u27cd', ['Mathematical Falling Diagonal', '\\']);
exports.UNICODE_MISTAKES.set('\u29f5', ['Reverse Solidus Operator', '\\']);
exports.UNICODE_MISTAKES.set('\u29f9', ['Big Reverse Solidus', '\\']);
exports.UNICODE_MISTAKES.set('\u29f9', ['Greek Vocal Notation Symbol-16', '\\']);
exports.UNICODE_MISTAKES.set('\u29f9', ['Greek Instrumental Symbol-48', '\\']);
exports.UNICODE_MISTAKES.set('\u31d4', ['CJK Stroke D', '\\']);
exports.UNICODE_MISTAKES.set('\u4e36', ['CJK Unified Ideograph-4E36', '\\']);
exports.UNICODE_MISTAKES.set('\u2f02', ['Kangxi Radical Dot', '\\']);
exports.UNICODE_MISTAKES.set('\u3001', ['Ideographic Comma', '\\']);
exports.UNICODE_MISTAKES.set('\u30fd', ['Katakana Iteration Mark', '\\']);
exports.UNICODE_MISTAKES.set('\ua778', ['Latin Small Letter Um', '&']);
exports.UNICODE_MISTAKES.set('\uff06', ['Fullwidth Ampersand', '&']);
exports.UNICODE_MISTAKES.set('\u16ed', ['Runic Cross Punctuation', '+']);
exports.UNICODE_MISTAKES.set('\u2795', ['Heavy Plus Sign', '+']);
exports.UNICODE_MISTAKES.set('\u{1029b}', ['Lycian Letter H', '+']);
exports.UNICODE_MISTAKES.set('\ufb29', ['Hebrew Letter Alternative Plus Sign', '+']);
exports.UNICODE_MISTAKES.set('\uff0b', ['Fullwidth Plus Sign', '+']);
exports.UNICODE_MISTAKES.set('\u2039', ['Single Left-Pointing Angle Quotation Mark', '<']);
exports.UNICODE_MISTAKES.set('\u276e', ['Heavy Left-Pointing Angle Quotation Mark Ornament', '<']);
exports.UNICODE_MISTAKES.set('\u02c2', ['Modifier Letter Left Arrowhead', '<']);
exports.UNICODE_MISTAKES.set('\u{1d236}', ['Greek Instrumental Symbol-40', '<']);
exports.UNICODE_MISTAKES.set('\u1438', ['Canadian Syllabics Pa', '<']);
exports.UNICODE_MISTAKES.set('\u16b2', ['Runic Letter Kauna', '<']);
exports.UNICODE_MISTAKES.set('\u276c', ['Medium Left-Pointing Angle Bracket Ornament', '<']);
exports.UNICODE_MISTAKES.set('\u27e8', ['Mathematical Left Angle Bracket', '<']);
exports.UNICODE_MISTAKES.set('\u2329', ['Left-Pointing Angle Bracket', '<']);
exports.UNICODE_MISTAKES.set('\u3008', ['Left Angle Bracket', '<']);
exports.UNICODE_MISTAKES.set('\u31db', ['CJK Stroke Pd', '<']);
exports.UNICODE_MISTAKES.set('\u304f', ['Hiragana Letter Ku', '<']);
exports.UNICODE_MISTAKES.set('\u{21fe8}', ['CJK Unified Ideograph-21FE8', '<']);
exports.UNICODE_MISTAKES.set('\u300a', ['Left Double Angle Bracket', '<']);
exports.UNICODE_MISTAKES.set('\uff1c', ['Fullwidth Less-Than Sign', '<']);
exports.UNICODE_MISTAKES.set('\u1400', ['Canadian Syllabics Hyphen', '=']);
exports.UNICODE_MISTAKES.set('\u2e40', ['Double Hyphen', '=']);
exports.UNICODE_MISTAKES.set('\u30a0', ['Katakana-Hiragana Double Hyphen', '=']);
exports.UNICODE_MISTAKES.set('\ua4ff', ['Lisu Punctuation Full Stop', '=']);
exports.UNICODE_MISTAKES.set('\uff1d', ['Fullwidth Equals Sign', '=']);
exports.UNICODE_MISTAKES.set('\u203a', ['Single Right-Pointing Angle Quotation Mark', '>']);
exports.UNICODE_MISTAKES.set('\u276f', ['Heavy Right-Pointing Angle Quotation Mark Ornament', '>']);
exports.UNICODE_MISTAKES.set('\u02c3', ['Modifier Letter Right Arrowhead', '>']);
exports.UNICODE_MISTAKES.set('\u{1d237}', ['Greek Instrumental Symbol-42', '>']);
exports.UNICODE_MISTAKES.set('\u1433', ['Canadian Syllabics Po', '>']);
exports.UNICODE_MISTAKES.set('\u{16f3f}', ['Miao Letter Archaic Zza', '>']);
exports.UNICODE_MISTAKES.set('\u276d', ['Medium Right-Pointing Angle Bracket Ornament', '>']);
exports.UNICODE_MISTAKES.set('\u27e9', ['Mathematical Right Angle Bracket', '>']);
exports.UNICODE_MISTAKES.set('\u232a', ['Right-Pointing Angle Bracket', '>']);
exports.UNICODE_MISTAKES.set('\u3009', ['Right Angle Bracket', '>']);
exports.UNICODE_MISTAKES.set('\u300b', ['Right Double Angle Bracket', '>']);
exports.UNICODE_MISTAKES.set('\uff1e', ['Fullwidth Greater-Than Sign', '>']);
exports.ASCII_NAMES = new Map();
exports.ASCII_NAMES.set(' ', 'Space');
exports.ASCII_NAMES.set('_', 'Underscore');
exports.ASCII_NAMES.set('-', 'Minus/Hyphen');
exports.ASCII_NAMES.set(',', 'Comma');
exports.ASCII_NAMES.set(';', 'Semicolon');
exports.ASCII_NAMES.set(':', 'Colon');
exports.ASCII_NAMES.set('!', 'Exclamation Mark');
exports.ASCII_NAMES.set('?', 'Question Mark');
exports.ASCII_NAMES.set('.', 'Period');
exports.ASCII_NAMES.set("'", 'Single Quote');
exports.ASCII_NAMES.set('"', 'Quotation Mark');
exports.ASCII_NAMES.set('(', 'Left Parenthesis');
exports.ASCII_NAMES.set(')', 'Right Parenthesis');
exports.ASCII_NAMES.set('[', 'Left Square Bracket');
exports.ASCII_NAMES.set(']', 'Right Square Bracket');
exports.ASCII_NAMES.set('{', 'Left Curly Brace');
exports.ASCII_NAMES.set('}', 'Right Curly Brace');
exports.ASCII_NAMES.set('*', 'Asterisk');
exports.ASCII_NAMES.set('/', 'Slash');
exports.ASCII_NAMES.set('\\', 'Backslash');
exports.ASCII_NAMES.set('&', 'Ampersand');
exports.ASCII_NAMES.set('+', 'Plus Sign');
exports.ASCII_NAMES.set('<', 'Less-Than Sign');
exports.ASCII_NAMES.set('=', 'Equals Sign');
exports.ASCII_NAMES.set('>', 'Greater-Than Sign');
