"use strict";
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
Object.defineProperty(exports, "__esModule", { value: true });
// EVERYTHING BELOW IS AUTOGENERATED. SEE SCRIPTS FOLDER FOR UPDATE SCRIPTS
const camelCase_1 = require("./regular/camelCase");
const caseSingleStatement_1 = require("./regular/caseSingleStatement");
const defaultExportSameBasename_1 = require("./regular/defaultExportSameBasename");
const doubleEquals_1 = require("./regular/doubleEquals");
const duplicateImportSource_1 = require("./regular/duplicateImportSource");
const emptyBlocks_1 = require("./regular/emptyBlocks");
const emptyMatches_1 = require("./regular/emptyMatches");
const getterReturn_1 = require("./regular/getterReturn");
const importDefaultBasename_1 = require("./regular/importDefaultBasename");
const inconsiderateLanguage_1 = require("./regular/inconsiderateLanguage");
const jsxKey_1 = require("./react/jsxKey");
const jsxNoCommentText_1 = require("./react/jsxNoCommentText");
const negationElse_1 = require("./regular/negationElse");
const noArguments_1 = require("./regular/noArguments");
const noAsyncPromiseExecutor_1 = require("./regular/noAsyncPromiseExecutor");
const noCatchAssign_1 = require("./regular/noCatchAssign");
const noChildrenProp_1 = require("./react/noChildrenProp");
const noCommaOperator_1 = require("./regular/noCommaOperator");
const noCompareNegZero_1 = require("./regular/noCompareNegZero");
const noCondAssign_1 = require("./regular/noCondAssign");
const noDebugger_1 = require("./regular/noDebugger");
const noDelete_1 = require("./regular/noDelete");
const noDeleteVars_1 = require("./regular/noDeleteVars");
const noDupeArgs_1 = require("./regular/noDupeArgs");
const noDuplicateCase_1 = require("./regular/noDuplicateCase");
const noDuplicateGroupNamesInRegularExpressions_1 = require("./regular/noDuplicateGroupNamesInRegularExpressions");
const noDuplicateKeys_1 = require("./regular/noDuplicateKeys");
const noEmptyCharacterClass_1 = require("./regular/noEmptyCharacterClass");
const noExplicitAny_1 = require("./regular/noExplicitAny");
const noExtraBooleanCast_1 = require("./regular/noExtraBooleanCast");
const noFunctionAssign_1 = require("./regular/noFunctionAssign");
const noImportAssign_1 = require("./regular/noImportAssign");
const noLabelVar_1 = require("./regular/noLabelVar");
const noMultipleSpacesInRegularExpressionLiterals_1 = require("./regular/noMultipleSpacesInRegularExpressionLiterals");
const noPosixInRegularExpression_1 = require("./regular/noPosixInRegularExpression");
const noReferenceToNonExistingGroup_1 = require("./regular/noReferenceToNonExistingGroup");
const noSetterReturn_1 = require("./regular/noSetterReturn");
const noShadowRestrictedNames_1 = require("./regular/noShadowRestrictedNames");
const noShorthandArrayType_1 = require("./regular/noShorthandArrayType");
const noTemplateCurlyInString_1 = require("./regular/noTemplateCurlyInString");
const noUnsafeFinally_1 = require("./regular/noUnsafeFinally");
const noVar_1 = require("./regular/noVar");
const preferBlockStatements_1 = require("./regular/preferBlockStatements");
const preferFunctionDeclarations_1 = require("./regular/preferFunctionDeclarations");
const preferTemplate_1 = require("./regular/preferTemplate");
const preferWhile_1 = require("./regular/preferWhile");
const restrictedGlobals_1 = require("./regular/restrictedGlobals");
const singleVarDeclarator_1 = require("./regular/singleVarDeclarator");
const sortImportExportSpecifiers_1 = require("./regular/sortImportExportSpecifiers");
const sparseArray_1 = require("./regular/sparseArray");
const stylePropObject_1 = require("./react/stylePropObject");
const undeclaredVariables_1 = require("./regular/undeclaredVariables");
const unsafeNegation_1 = require("./regular/unsafeNegation");
const unusedVariables_1 = require("./regular/unusedVariables");
exports.lintTransforms = [
    camelCase_1.default,
    caseSingleStatement_1.default,
    defaultExportSameBasename_1.default,
    doubleEquals_1.default,
    duplicateImportSource_1.default,
    emptyBlocks_1.default,
    emptyMatches_1.default,
    getterReturn_1.default,
    importDefaultBasename_1.default,
    inconsiderateLanguage_1.default,
    jsxKey_1.default,
    jsxNoCommentText_1.default,
    negationElse_1.default,
    noArguments_1.default,
    noAsyncPromiseExecutor_1.default,
    noCatchAssign_1.default,
    noChildrenProp_1.default,
    noCommaOperator_1.default,
    noCompareNegZero_1.default,
    noCondAssign_1.default,
    noDebugger_1.default,
    noDelete_1.default,
    noDeleteVars_1.default,
    noDupeArgs_1.default,
    noDuplicateCase_1.default,
    noDuplicateGroupNamesInRegularExpressions_1.default,
    noDuplicateKeys_1.default,
    noEmptyCharacterClass_1.default,
    noExplicitAny_1.default,
    noExtraBooleanCast_1.default,
    noFunctionAssign_1.default,
    noImportAssign_1.default,
    noLabelVar_1.default,
    noMultipleSpacesInRegularExpressionLiterals_1.default,
    noPosixInRegularExpression_1.default,
    noReferenceToNonExistingGroup_1.default,
    noSetterReturn_1.default,
    noShadowRestrictedNames_1.default,
    noShorthandArrayType_1.default,
    noTemplateCurlyInString_1.default,
    noUnsafeFinally_1.default,
    noVar_1.default,
    preferBlockStatements_1.default,
    preferFunctionDeclarations_1.default,
    preferTemplate_1.default,
    preferWhile_1.default,
    restrictedGlobals_1.default,
    singleVarDeclarator_1.default,
    sortImportExportSpecifiers_1.default,
    sparseArray_1.default,
    stylePropObject_1.default,
    undeclaredVariables_1.default,
    unsafeNegation_1.default,
    unusedVariables_1.default,
];
